### ISSUE TITLE
Change tk.listbox to ttk.treeview -15 hours

### ISSUE THREAD

**Issue by Marinius1** [Marinius1/CS2450--601_Team-3#42]
All listboxes need to be changed to ttk.treeview in order to connect a styled, sized, and dynamic font evenly throughout the entire program. 

Definitely a milestone 4 goal.

**Comment by idobbins** [comment]
We rediscovered why we did not want to do this with a TreeView. We kept the initial implementation and hoisted the click listener logic into its own module. We have started with the dynamic font-size implementation. I would say it is about 85% implemented at this point.

**Comment by idobbins** [comment]
Closing this issue but will create another for the dynamic font size implementation.
