### ISSUE TITLE
Possibly move event listeners on scrolling to separate threads.

### ISSUE THREAD

**Issue by Marinius1** [Marinius1/CS2450--601_Team-3#45]
Large windows performance issues during scrolling on the payroll page brought this up.
I know it's outside of the scope of this class, but at the end of Milestone 4, after ALL other issues are resolved, we might
want to try this out.
Also Tkinter sucks...
Also single threaded software based rendering is garbage.
Also I hate Tkinter.

**Comment by idobbins** [comment]
closing because 'wontfix'
